version: "3.7"

services:

  nginx:
    container_name: plateaux_nginx
    build:
      context: ./nginx
      target: nginx_${ENV}
    restart: always
    volumes:
      - ./../client/app/:/application:ro
    ports:
      - ${HTTP_PORT}:8080
    networks:
      - plateaux

  server:
    container_name: plateaux_server
    build:
      context: ./server
    restart: always
    entrypoint: /application/entrypoint.sh
    volumes:
      - ./../server:/application/server:rw
    networks:
      - plateaux

  client:
    container_name: plateaux_client
    build:
      context: ./client
      target: client_${ENV}
    restart: always
    entrypoint: /application/entrypoint.sh
    volumes:
      - ./../client:/application/client:rw
    networks:
      - plateaux

networks:
  plateaux:
    driver: bridge
